#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
python3 ${DIR}/ep-0118-ups.py

#echo "Bus Voltage: 5.224 V"
#echo "Bus Current: 73.000 mA"
#echo "Power: 380.488 mW"
#echo "Shunt voltage: 5.010 mV"
